name: injest-data-app

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: prefect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  prefect:
    image: prefecthq/prefect:3.1.3.dev3-python3.9
    restart: always
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:mysecretpassword@db:5432/prefect
      PREFECT_API_DATABASE_ECHO: false
      PREFECT_API_DATABASE_MIGRATE_ON_START: true
      PREFECT_API_URL: http://0.0.0.0:4200/api
      PREFECT_SERVER_API_HOST: "0.0.0.0"
      PREFECT_SERVER_API_PORT: "4200"
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network

    command: ["sh", "-c", "prefect server start --host 0.0.0.0 --port 4200"]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432
      PREFECT_API_URL: http://prefect:4200/api
    volumes:
      - .:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - db
      - prefect
    networks:
      - app_network
    command: ["/bin/sh", "-c", "/wait-for-it.sh db:5432 -t 60 && /wait-for-it.sh prefect:4200 -t 60 && python /app/main.py"]

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
